site_name: My Documentation Site
site_url: https://example.com

theme:
  name: mkdocs  # Using the default theme

plugins:
  - search  # Enable the search plugin
  - mkdocs_sample_plugin:
      text: "This is custom text added by the plugin."
      underline: true  # This will underline the custom text

nav:
  - Home: index.md
  - Example: example.md